#!/usr/bin/env python
"""
    %prog [options] meds_file output_file


Description

    Extract the catalog and meta data from a MEDS file and write
    to a new file
"""

import sys
from optparse import OptionParser
import meds

parser=OptionParser(__doc__)

def main():
    options, args = parser.parse_args(sys.argv[1:])

    if len(args) < 2:
        parser.print_help()
        sys.exit(1)

    meds_file=args[0]
    out_file=args[1]

    meds.extract_catalog(meds_file, out_file)
 
main()
