name: tests

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  tests:
    name: tests
    strategy:
      matrix:
        pyver: ["3.9", "3.10", "3.11"]

    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.pyver }}
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-variant: Mambaforge
          use_mamba: true

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda install -q mamba

          # requirements for meds
          mamba install -q --file requirements.txt

          # installs for testing
          mamba install -q \
            pip \
            setuptools \
            flake8 \
            pytest-cov

          python -m pip install -e .

      - name: lint
        shell: bash -l {0}
        run: |
          flake8 meds

      - name: test
        shell: bash -l {0}
        run: |
          pytest -v --cov=meds --cov-report term-missing meds
